function [ptor,Jtor,dJtordq] = fcn_torso_p_J_dJdq(in1,in2,in3)
%fcn_torso_p_J_dJdq
%    [PTOR,Jtor,dJtordq] = fcn_torso_p_J_dJdq(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    23-Nov-2025 16:29:10

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
ptor = [q1;q2;q3];
if nargout > 1
    Jtor = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,13]);
end
if nargout > 2
    dJtordq = [0.0;0.0;0.0];
end
end
